#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Exception\CommandNotFoundException;

$app = new App([
    'app_path' => __DIR__ . '/app/Command',
    'debug' => true
], "\e[92m
    ___                              ____                      __                __         
   /   |  ______   ______ _____     / __ \____ _      ______  / /___  ____ _____/ /__  _____
  / /| | / ___/ | / / __ `/ __ \   / / / / __ \ | /| / / __ \/ / __ \/ __ `/ __  / _ \/ ___/
 / ___ |/ /   | |/ / /_/ / / / /  / /_/ / /_/ / |/ |/ / / / / / /_/ / /_/ / /_/ /  __/ /    
/_/  |_/_/    |___/\__,_/_/ /_/  /_____/\____/|__/|__/_/ /_/_/\____/\__,_/\__,_/\___/_/     
                                                         
\e[39mArvan Downloader \e[42m v1.0.0 \033[0m
By \e[31mDaniel Yousefi Far \e[34m<yousefifar.dev> \033[0m
");

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->getPrinter()->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->getPrinter()->error("An error occurred:");
        $app->getPrinter()->error($exception->getMessage());
    }
    return 1;
}

return 0;